LiskHQ/lisk-elements

- .gitignore
- eslint_ecma5.json
- package.json
Integrating Istanbul coverage metric.
Updating package.json dependencies.
As mentioned in Issue #10
Refining rules defined in `eslint_ecma5.json`.
> Adding test coverage metric with eslint refinements

- lib/api/liskApi.js
Closes #93
Needed for https://github.com/LiskHQ/lisk-nano/issues/106
> Add ports to testnet and ssl in lisk.api().listPeers() - Closes #93

- lib/api/liskApi.js
As the nodes got recently ssl enabled.
> Use node0X.lisk.io for ssl peers

- lib/transactions/crypto.js
- lib/transactions/transfer.js
- test/transactions/transfer.js
~~Merge #199 first~~
Closes #145
> Add functions to create dapp deposits/withdrawals - Closes #145

- package-lock.json
- package.json
- yarn.lock
~~Merge #190 first~~
Mocha's `--watch` flag interacted oddly with `js-nacl` (which is based on `Emscripten` and does complicated things with modules). Mocha's policy when `--watch` doesn't work seems to be to recommend other libraries (see e.g. https://github.com/mochajs/mocha/issues/1780), which is why I added `chokidar`.
Closes #186
> Add mocha watch scripts - Closes #186

- test/transactions/dapp.js
- test/transactions/delegate.js
- test/transactions/multisignature.js
- test/transactions/signature.js
- test/transactions/transaction.js
- test/transactions/transfer.js
- test/transactions/vote.js
Closes #274 
Merge #282 first
Commit c8aa202 affects other modules, but was there before #178 was split up.
> Make vote transaction tests atomic

- src/api/liskApi.js
- src/api/utils.js
- test/api/utils.js
Closes #279 
Line 24 registers as partially uncovered, but this should be resolved in  #309.
> Make api utils tests atomic - Closes #279

- src/transactions/multisignature.js
- test/transactions/dapp.js
- test/transactions/delegate.js
- test/transactions/multisignature.js
- test/transactions/signature.js
- test/transactions/transaction.js
- test/transactions/vote.js
Closes #354 
This PR removes the `signTransaction` function from the `multisignature` transaction creation module so I didn't have to refactor the tests. It's just a wrapper for a crypto function, and we don't have an analogue in any of the other transaction creators.
> Remove crypto stubbing - Closes #354

- .babelrc
- Gruntfile.js
- package.json
Partial solution to #348 
- fixes undefined `sinon` problem
- includes `rewire` plugin for browsertest build
- includes all test files in browsertest build
- adds an npm script for browsertest build
- **does not fix undefined `rewire` methods problem**
> Improve browsertest infrastructure

- test/.eslintrc.json
- test/api/liskApi.js
- test/api/privateApi.js
- test/api/utils.js
- test/setup.js
- test/transactions/dapp.js
- test/transactions/delegate.js
- test/transactions/multisignature.js
- test/transactions/signature.js
- test/transactions/transaction.js
- test/transactions/transfer.js
- test/transactions/vote.js
Closes #365 
Couldn't see a way to use fake timers with the sandbox without rewriting the `slots` tests, which is beyond the scope of this issue.
Also, I wanted to just add an `afterEach` hook in `setup.js`, but apparently this is not possible for require'd scripts, which is why there's this `afterEach(() => sandbox.restore());` at the top of each relevant test file. See https://github.com/mochajs/mocha/issues/764
> Use sinon sandboxes - Closes #365

- ISSUE_TEMPLATE.md
Per discussion in #395, updated the link in ISSUE_TEMPLATE.md with a relative link, based on the one that is in CONTRIBUTING.md (line 24), so that regardless of branch, it will work as long as the file is present in the same branch.
> Code of Conduct Link Update in ISSUE_TEMPLATE.md (Relative Notation) - Fixes #392

- src/transactions/0_send.js
- src/transactions/0_sendFromMultisignatureAccount.js
- src/transactions/1_registerSecondSignature.js
- src/transactions/2_registerDelegate.js
- src/transactions/3_castVotes.js
- src/transactions/4_registerMultisignatureAccount.js
- src/transactions/5_createDapp.js
- src/transactions/6_transferIntoDapp.js
- src/transactions/7_transferOutOfDapp.js
- test/transactions/0_send.js
- test/transactions/0_sendFromMultisignatureAccount.js
- test/transactions/1_registerSecondSignature.js
- test/transactions/2_registerDelegate.js
- test/transactions/3_castVotes.js
- test/transactions/4_registerMultisignatureAccount.js
- test/transactions/5_createDapp.js
- test/transactions/6_transferIntoDapp.js
- test/transactions/7_transferOutOfDapp.js
Use single option parameter as an argument for functions in these `transaction` modules:
close #337
> Use single options parameter as argument for functions - Close #337

- src/crypto/convert.js
- src/crypto/hash.js
- src/crypto/index.js
- src/crypto/keys.js
- src/crypto/sign.js
- src/transactions/utils/getTransactionHash.js
- test/crypto/convert.js
- test/crypto/hash.js
- test/crypto/keys.js
- test/crypto/sign.js
- test/transactions/utils/getTransactionHash.js
- test/transactions/utils/index.js
Closes #401 
In `src/crypto/hash.js` I disabled an eslint rule for preferring default exports thinking we might want more hash functions in future, but an alternative would be to make `getSha256Hash` the default export instead.
> :recycle: Move getTransactionHash into transactions module - Closes #401

- README.md
Link to CDN for lisk-js was broken, possibly because it was pointing to the development branch rather than master branch.
> Fix CDN link in README.md

- Jenkinsfile
- package.json
Closes #466
This just adds a basic check to see if requiring the build distribution for node errors. In the issue it suggested running the full test suite against the built files, so we might need to discuss this before merging.
> Add node build check - Closes #466

- package-lock.json
- package.json
- src/cryptography/convert.js
- src/cryptography/encrypt.js
- src/transactions/utils/getTransactionBytes.js
- src/transactions/utils/validation.js
- test/cryptography/convert.js
- test/cryptography/encrypt.js
- test/transactions/3_castVotes.js
- test/transactions/4_registerMultisignatureAccount.js
- test/transactions/utils/validation.js
Closes #561 
- Changed `hexToBuffer` behavior to mimic node version >= 8 in all versions.
- Changed `Buffer.from` to use `hexToBuffer`
Run test against
* v6.12.3
* v7.10.1
* v8.9.4
* v9.5.0
> Add multiple node.js version support - Closes #561

- Jenkinsfile
Trying to clean up `/logs/*` without it being created ever.
Remove always cleanup step
`npm t`
* The PR solves #590
* Tests pass
> Remove to delete never existing dir logs in lisk-elements Jenkins - Closes #590

- src/constants/index.js
- src/transactions/utils/getTransactionBytes.js
- test/constants/constants.js
- test/transactions/utils/getTransactionBytes.js
We allowed all amounts as inputs to GTB.
Added checks for amount range. We might want to extend this to other properties too?
* The PR solves #543 
* Tests pass
> Check amount in getTransactionBytes - Closes #543

- src/api_client/resources/accounts.js
- src/api_client/resources/delegates.js
- test/api_client/resources/accounts.js
- test/api_client/resources/delegates.js
- Update on APIEndpoint update on lisk-core
- Singular name of resource method even though API endpoints were plural.
- Change API endpoint and fixed method name
- Update name to match API endpoints
* The PR solves #602 
* Tests pass
> Update APIClient endpoint and function names - Closes #602

- package.json
Closes #579
We didn't have a script for running browsertests in headed mode (useful for debugging).
Added a script.
`npm run test:browser:headed`
* The PR solves #579 
* Tests pass
> Add headed browsertest npm script - Closes #579

- test/api_client/api_resource.js
Closes #560
We weren't making use of chai-as-promised.
I applied it where possible. The problem was in most cases we were making assertions on things other than the resolution value of the relevant promise, so chai-as-promised couldn't be used.
`npm test`
* The PR solves #560 
* Tests pass
> Use chai-as-promised where possible - Closes #560

- test/api_client/index.js
src/api_client/index.js did not have tests covering the exports
Add tests to cover if it is exporting what we expect
`npm test`
* The PR solves #595
* Tests pass
> Add api client export to test

- src/passphrase/validation.js
- test/passphrase/validation.js
Locate whitespaces was error prone since it looks for consecutive whitespaces, whitespaces are naturally part of mnemonic passphrases 
Rename locateWhitespaces function to locateConsecutiveWhitespaces
`npm test`
* The PR solves #608
* Tests pass
> Rename locate whitespaces to locate consecutive whitespaces

- src/api_client/api_resource.js
- src/api_client/constants.js
- test/api_client/api_resource.js
- test/api_client/constants.js
If randomizeNode was not set to true, it will retry forever to the same node.
limit the number of try to 3, if randomizeNode is set to false.
`npm test`
* The PR solves #587 
* Merge after #596 
* Tests pass
> Update retry policy - Closes #587

- src/cryptography/convert.js
- test/cryptography/convert.js
cryptography.toAddress did not have any input validation
Adding validation for buffer !== Buffer.from(buffer).slice(0, 8)
`npm test`
* The PR solves #607
* Tests pass
> Add check for buffer length passed to cryptography toAddress - Closes #607

- test/cryptography/convert.js
Wrong input of ed2curve functions, `string` instead of `Buffer`
- Fix the input to use `Buffer`
- Recalculated the result hash using library. [https://www.npmjs.com/package/ed2curve](https://www.npmjs.com/package/ed2curve)
`npm test`
* The PR solves #551
* Tests pass
> Fix Ed2Curve usage in test - Closes #551

- src/transactions/utils/wrap_transaction_creator.js
- test/transactions/1_register_second_passphrase.js
- test/transactions/2_register_delegate.js
- test/transactions/4_register_multisignature_account.js
- test/transactions/5_create_dapp.js
- test/transactions/6_transfer_into_dapp.js
- test/transactions/utils/wrap_transaction_creator.js
Lisk-core sets `recipientId` as required field of string, on all the transaction related API.
Therefore, creating transaction with `null` will not pass the API validation.
#615 attempted to fix it for transaction type 2, but it applies to transactions `1, 2, 4, 5, 6`, therefore, more generic solution was needed
Change default value of transaction to be `empty string`
`npm test`
create each transaction of type 1, 2, 4, 5, and 6, then send it to core `1.0.0` API.
* The PR solves #614 
* The PR is different approach of #615 
* Tests pass
> Fix default recipientId to be empty string

- src/transactions/utils/get_transaction_bytes.js
Dapp transactionId did not match to `lisk-core`.
When we create the buffer for the asset field for Dapp, we were doing
```
const typeBuffer = Buffer.alloc(4, type);
const categoryBuffer = Buffer.alloc(4, category);
```
This would fill each byte with the second argument of the `alloc`
```
Buffer.alloc(4, 3)
<Buffer 03 03 03 03>
```
However what `lisk-core` was expecting was
```
<Buffer 03 00 00 00>
```
which is done in [here](https://github.com/LiskHQ/lisk/blob/ab613eb7da7952169a1457cd1274c588612152be/logic/dapp.js#L287-L290)
Instead of allocating to each bytes,
```
const categoryBuffer = Buffer.alloc(4);
categoryBuffer.writeIntLE(category, 0);
```
Create transaction and send it to lisk-core
* The PR solves #616 
* All new code was formatted with …
> Fix buffer allocation for dapp asset - Closes #616

- src/api_client/api_resource.js
- test/api_client/api_resource.js
When APIClient gets non-2xx status code, it does not throw an error.
If we return the body as the way currently work, there is no good way to check if it is an error or not from user.
Check if the status code is greater than 300 (>= 300), then if it's 300 then throw an error.
If API supplies error message, throw an error with the message.
If not, return with unknown error.
`npm test` and try to use it with Lisk core 1.0.0
* The PR solves #621
* Tests pass
> Change APIClient to throw error when API returns non 2xx - Closes #621

- src/api_client/api_client.js
- src/lisk-constants/index.js
- test/api_client/api_client.js
- test/lisk-constants/index.js
We didn't have constants for betanet. Or an API client.
I added constants for betanet, and a helper function for creating an API client.
`npm t`
* The PR solves #628 
* Tests pass
> Add betanet constants - Closes #628

- src/cryptography/convert.js
- src/cryptography/keys.js
- test/cryptography/convert.js
- test/cryptography/keys.js
`getAddress` was a confusing function name, and was used on betanet to get the address from a passphrase, even though it expected a public key, resulting in loss of funds.
I removed `getAddress` and added a specific `getAddressFromPassphrase` function.
`npm start` and then `LiskJS.cryptography.getAddressFromPassphrase(myPassphrase)`
* The PR solves #634 
* Tests pass
> Rework getAddress - Closes #634

- src/api_client/api_client.js
- test/api_client/api_client.js
Although nethash was not required from `core` API, it was required in the APIClient.
Remove `nethash` from required constructor input, and read it from optional field.
```
const client = elements.APIClient(['http://localhost:4000']);
client.node.getConstants().then(console.log);
```
* The PR solves #646
* Tests pass
> Change nethash to optional - Closes #646

- src/api_client/api_client.js
- src/api_client/constants.js
- src/lisk-constants/index.js
- src/transactions/index.js
- test/api_client/api_client.js
- test/api_client/constants.js
- test/lisk-constants/index.js
- test/transactions/index.js
transaction constant was not exposed, and constants that are used only in APIClient was in general constants
Expose constants from transaction
Expose APIClient constants
```
elements.transaction.constants;
elements.APICleint.constants;
```
* The PR solves #636 
* Tests pass
> Refactor constants location and export path - Closes 636

- bin/prestart.sh
We built everything prestart, even though only building for node was needed.
Changed `npm run build` to `npm run build:node` in the prestart script.
`npm start` then `y` to build.
* The PR solves #652 
* Tests pass
> Only build for node in prestart script - Closes #652

- src/api_client/api_resource.js
- src/api_client/constants.js
- test/api_client/constants.js
API_RECONNECT_MAX_RETRY_COUNT was exposed, but it should not be configurable.
Remove from exposed constants and move it to where it was used.
`console.log(LiskJS.APIClient.constnats)`
* The PR solves #661 
* Tests pass
> Remove reconnect max count - Closes #661

- src/transactions/utils/format.js
- src/transactions/utils/index.js
- test/transactions/utils/format.js
- test/transactions/utils/index.js
We didn't have convenience functions for switching between LSK amounts and the smallest denomination.
Added functions for that.
`npm t`
* The PR solves #635 
* Tests pass
> Add functions for converting between LSK and Beddows - Closes #635

- package.json
- src/cryptography/sign.js
- src/lisk-constants/index.js
- test/cryptography/sign.js
- test/lisk-constants/index.js
Lisk signed message doesn't have a header prefix
Calculate message signature with this formula:
~~sign (Lisk Signed Message:\n + message length + message)~~
```
digest = sha256(sha256(
varint(len(prefix)) + prefix + varint(len(message)) + message
))
sign(dugest)
```
run tests
* The PR solves #673 
* Tests pass
> Add prefix bytes to signed message - Closes#673

- package.json
If installing using npm via GitHub (e.g. specifying a GitHub commit in a project's `package.json`), `dist-node` would be missing, leading to an incomplete installation.
Added a `postinstall` check to see if the `dist-node` files exist, and if not build them.
* The PR solves #686 
* Tests pass
> Add conditional build postinstall

- src/api_client/resources/delegates.js
We weren't sorting delegates appropriately.
I fixed `getStandby` to use a valid sort order, and changed `get` to sort by `rank:asc` (see LiskHQ/lisk#2138).
* The PR solves #691 
* Tests pass
> Sort delegates properly in API call

- Jenkinsfile
Jenkinsfile was using functions shared across projects that can be imported now from https://github.com/LiskHQ/lisk-jenkins
Remove functions and add import
Tested in Jenkins itself
> Use shared jenkins library

- src/cryptography/convert.js
- src/cryptography/encrypt.js
- test/cryptography/convert.js
- test/cryptography/encrypt.js
We didn't output the default number of iterations when encrypting passphrases.
Better to be explicit.
Encrypt a passphrase without specifying the number of iterations.
* The PR solves #685 
* Tests pass
> Output default iterations when encrypting passphrases

- src/api_client/constants.js
- test/api_client/api_client.js
We were using http on testnet.
Updated testnet node to use https.
`lisk.APIClient.createTestnetAPIClient().transactions.get().then(console.log)`
* The PR solves #703 
* Tests pass
> Update testnet node to use https - Closes #703

- packages/lisk-cryptography/src/convert.js
- packages/lisk-cryptography/src/encrypt.js
- packages/lisk-cryptography/test/convert.js
- packages/lisk-cryptography/test/encrypt.js
Closes #688
We had no validation when decrypting passphrases, with unhelpful error messages.
Added validation and helpful error messages.
Try to decrypt a passphrase with some missing parameters.
* The PR solves #688 
* Tests pass
> Add validation to decrypt passphrase - Closes #688

- packages/lisk-api-client/src/api_client.js
- packages/lisk-api-client/test/api_client.js
lisk-elements is throwing Refused to set unsafe header “User-Agent”warning when it's used in browsers.
I updated getUserAgent function to return empty object when clientOptions were not provided.
should not set User-Agent header when client options were not given
* The PR solves #696 
* Tests pass
> Disable user-agent header when client options were not provided - Closes #696

- package.json
- src/cryptography/convert.js
Using `.reverse` on buffers isn't supported in the React Native/Android environment.
Used a library which will implement reverse for buffers.
Try to use `getFirstEightBytesReversed` in particular (plus other functions) in React Native/Android.
* The PR solves #710 
* Tests pass
> Use React Native/Android-compatible buffer reverse function - Closes #710

- src/lisk-constants/index.js
- test/transactions/utils/format.js
- test/transactions/utils/get_transaction_bytes.js
The `MAX_TRANSACTION_AMOUNT` constant did not conform to Core's behaviour.
Reduced it to the value of the initial supply in line with Core's validation check.
Try creating transactions with amounts larger/smaller than that amount.
* The PR resolves #763 
* Tests pass
> Update maximum transaction amount - Closes #763

- package.json
Lerna was not running `link` occasionally 
Upgrading lerna version seems to fix the issue
```
npm run clean
npm run clean:node_modules
npm install
npm run build
```
* The PR resolves #796 
* Tests pass
> Upgrade lerna and lint-staged

- package-lock.json
- packages/lisk-cryptography/README.md
- packages/lisk-cryptography/benchmark/nacl.js
- packages/lisk-cryptography/package-lock.json
- packages/lisk-cryptography/package.json
We do not have any benchmark to evaluate the performance of tweetnacl vs. sodium-native.
Create benchmark for nacl functions.
In packages/lisk-cryptography:
`npm i -D benchmark sodium-native`
`npx babel-node ./benchmark/nacl`
* The PR resolves #789 
* Tests pass
> 789 - Add benchmark for nacl libraries

- tslint.json
Filename to be snake_case instead of camelCase
Add rule in `tslint.json` file `"file-name-casing": "snake-case"`
`npm run lint`
* The PR resolves #811
* Tests pass
> Change tslint filename rule from camelCase to Snake_case - Closes #811

- tslint.json
We currently have a lot of code where we check string, undefined null existence.
Also, we are using `const a = input || defaultValue` this kind of codes everywhere.
Therefore, temporally disabling it
* The PR resolves #818 
* Tests pass
> Disable strict-boolean-expressions - Closes #818

- tslint.json
Removing `completed-docs` rules we currently don't use JSDocs and we have documentation in other format.
* The PR resolves #819
* Tests pass
> Disable completed-docs rule for tslint - Closes #819

- packages/lisk-client/package.json
- packages/lisk-elements/package.json
Build script for the browser publish was removed pre 1.0 release, but at some point only the package.json script came back
Remove the unneeded npm script
* The PR resolves #836
* Tests pass
> Remove browser publish script

- packages/lisk-transactions/test/utils/get_transaction_bytes.ts
`getTransactionBytes` test suite had outdated test to check for allowing 0 transfer transactions.
Removed outdated test
npm run test
* The PR resolves #837 
* Tests pass
> Remove outdated zero transfer amount test - Closes #837

- packages/lisk-transactions/src/utils/validation/validation.ts
- packages/lisk-transactions/test/utils/validation/validation.ts
- packages/lisk-transactions/test/utils/validation/validator.ts
Address validation allowed leading zeros and inclusion of `.` character.
Updated `validateAddress` in utils.
npm run test
* The PR resolves #832 
* Tests pass
> Update address validation - Closes #832

- packages/lisk-transactions/src/index.ts
Because we will have new transaction type on the next 2.1 version, we should not actively expose the type otherwise it will be a breaking change again.
* The PR resolves #848 
* Tests pass
> Remove transaction interface from exposing

- packages/lisk-api-client/package.json
- packages/lisk-api-client/src/api_client.ts
- packages/lisk-api-client/src/constants.ts
- packages/lisk-cryptography/package.json
- packages/lisk-cryptography/src/constants.ts
- packages/lisk-cryptography/src/sign.ts
- packages/lisk-transactions/package.json
- packages/lisk-transactions/src/constants.ts
- packages/lisk-transactions/src/utils/get_transaction_bytes.ts
- packages/lisk-transactions/src/utils/time.ts
- packages/lisk-transactions/src/utils/validation/validation.ts
A lot of constants were in `lisk-constants` package but all of them were currently package specific constants.
Move all the constants to the specific packages, but keep the `lisk-constants` as it is because it will
remove everything. 
`npm t`
* The PR resolves #785 
* Tests pass
> Move constants to specific packages - Closes #785

- packages/lisk-api-client/src/api_method.ts
- packages/lisk-api-client/src/api_types.ts
- packages/lisk-api-client/test/api_method.ts
- packages/lisk-cryptography/src/convert.ts
- packages/lisk-cryptography/src/encrypt.ts
- packages/lisk-cryptography/test/convert.ts
- packages/lisk-cryptography/test/nacl/nacl.ts
After migration to typescript, there were small missing unit test
Add unit tests and fix small issue
`npm t`
* The PR resolves #844 
* Tests pass
> Add missing unit test after typescript migration - Closes #844

- packages/lisk-api-client/src/index.ts
- packages/lisk-api-client/test/index.ts
- packages/lisk-client/src/index.ts
- packages/lisk-cryptography/src/index.ts
- packages/lisk-cryptography/test/index.ts
- packages/lisk-elements/src/index.ts
- packages/lisk-passphrase/src/index.ts
- packages/lisk-passphrase/test/index.ts
- packages/lisk-transactions/src/0_transfer.ts
- packages/lisk-transactions/src/1_register_second_passphrase.ts
- packages/lisk-transactions/src/3_cast_votes.ts
- packages/lisk-transactions/src/create_signature_object.ts
- packages/lisk-transactions/src/index.ts
- packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.ts
- packages/lisk-transactions/src/utils/get_transaction_bytes.ts
- packages/lisk-transactions/src/utils/get_transaction_hash.ts
- packages/lisk-transactions/src/utils/get_transaction_id.ts
- packages/lisk-transactions/src/utils/prepare_transaction.ts
- packages/lisk-transactions/src/utils/sign_and_verify.ts
- packages/lisk-transactions/src/utils/sign_raw_transaction.ts
- packages/lisk-transactions/src/utils/validation/validation.ts
- packages/lisk-transactions/test/0_transfer.ts
- packages/lisk-transactions/test/4_register_multisignature_account.ts
- packages/lisk-transactions/test/index.ts
- packages/lisk-transactions/test/utils/get_transaction_id.ts
- packages/lisk-transactions/test/utils/sign_and_verify.ts
- packages/lisk-transactions/test/utils/validation/validation.ts
export default was not standard, and it was mainly for babel users.
Now it's in typescript, and the original main user was front-end, so we keep the functionality for client, but remove from all other packages.
Remove default export from all the packages except `@liskhq/lisk-client`
`npm test` or
`npm run build` and try to use each pakcages
* The PR resolves #859 
* Tests pass
> Remove default export from child packages and lisk-elements

- packages/lisk-api-client/src/api_client.ts
- packages/lisk-api-client/src/api_method.ts
- packages/lisk-api-client/src/api_resource.ts
- packages/lisk-api-client/src/api_types.ts
Define type for `APIClient.constants` and wrong type definition of `APIHandler`
changed to concrete type, and remove resource from the type for APIHandler. 
Check the built file and make sure it's typed correctly.
* The PR resolves #863 
* Tests pass
> Fix type definition for APIClient - Closes #863

- packages/lisk-passphrase/src/validation.ts
- packages/lisk-passphrase/test/validation.ts
Validating passphrase was limited to exactly 12 words.
Add another input field to adjust expected words count
`npm t`
or
```
passphrase.getPassphraseValidationErrors('post dumb recycle buddy round normal scrap better people corn crystal again never shrimp kidney') // this should be error
passphrase.getPassphraseValidationErrors('post dumb recycle buddy round normal scrap better people corn crystal again never shrimp kidney', undefined, 15)
```
* The PR resolves #862 
* Tests pass
> Add valid number of words to validate passphrase

- packages/lisk-cryptography/src/index.ts
Cryptography module constants were not exposed
Expose constants from cryptography index.ts
```
cd packages/lisk-client
npm start
lisk.cryptography.constants
```
* The PR resolves #906 
* Tests pass
> Expose constants from lisk-cryptography - Closes #906

- packages/lisk-p2p/src/peer_selector.ts
- packages/lisk-p2p/test/unit/peer_selector.ts
Sometimes peer selection algorithm is not returning the requested `n` number of peers.
Improved selection peer algorithm in the section where we were handling `n` number of requested peers.
Run `npm t` multiple times, it will not fail now.
* The PR resolves #925 
* Tests pass
> Select peers doesn't always give 'n' requested peers - Closes#925

- packages/lisk-p2p/test/tsconfig.json
- packages/lisk-p2p/tsconfig.json
- packages/lisk-p2p/types/socketcluster-client/index.d.ts
- packages/lisk-p2p/types/socketcluster-server/index.d.ts
Socket-cluster doesn't have official type definition so define minimal type definition for socket cluster server needed.
Add type definition file under `types` folder for `socketcluster-server` and `socketcluster-client`
`npm run build` 
`npm t`
* The PR resolves #918
* Tests pass
> Add type definition for socketcluster

- packages/lisk-api-client/src/api_method.ts
- packages/lisk-api-client/src/api_resource.ts
- packages/lisk-api-client/src/api_types.ts
- packages/lisk-api-client/src/errors.ts
- packages/lisk-api-client/src/resources/accounts.ts
- packages/lisk-api-client/src/resources/blocks.ts
- packages/lisk-api-client/src/resources/dapps.ts
- packages/lisk-api-client/src/resources/delegates.ts
- packages/lisk-api-client/src/resources/node.ts
- packages/lisk-api-client/src/resources/peers.ts
- packages/lisk-api-client/src/resources/signatures.ts
- packages/lisk-api-client/src/resources/transactions.ts
- packages/lisk-api-client/src/resources/voters.ts
- packages/lisk-api-client/src/resources/votes.ts
- packages/lisk-api-client/test/api_method.ts
- packages/lisk-api-client/test/api_resource.ts
- packages/lisk-api-client/test/errors.ts
APIError did not have enough information to show proper error on the user side.
Add `errors` from APIResponse if exists in the error.
```
cd packages/lisk-client
npm start
client = lisk.APIClient.createTestnetAPIClient()
client.votes.get({ "random": 1 }).catch((err) => console.log(err.message))
client.votes.get({ "random": 1 }).catch((err) => console.log(err.errno))
client.votes.get({ "random": 1 }).catch((err) => console.log(err.errors))
```
* ~~Merge After #914~~
* The PR resolves #916 
* Tests pass
> Extend APIError to have errors from core

- packages/lisk-p2p/src/p2p.ts
- packages/lisk-p2p/src/p2p_types.ts
- packages/lisk-p2p/src/peer.ts
- packages/lisk-p2p/src/peer_pool.ts
- packages/lisk-p2p/test/integration/p2p.ts
P2P node needs to be able start, connect to seed peers and initiate discovery.
As part of this, basic peer management functionality is required.
Implemented:
- Basic node start functionality.
- Basic peer management.
- Initiate peer discovery through seed nodes.
- Basic peer connection.
- Peer request() and send() methods.
- Cleanup of existing code.
`npm test`
* The PR partially resolves #894 and #895 
* Tests pass
> Initialization start(), stop() and peer management - Addresses #894 and #895 
