README.md

The other transactions call were wrong. Now fixed.

fixed wrong call

---

lib/constants.js
lib/transactions/dapp.js
lib/transactions/delegate.js
lib/transactions/multisignature.js
lib/transactions/signature.js
lib/transactions/transaction.js
lib/transactions/transfer.js
lib/transactions/vote.js
test/tests.js

I have moved fees to constants.

Improvement of constants

---

eslint_ecma5.json

Setup EsLint as inspired by airbnb coding style.
Closes #8.

Setup static code analysis

---

README.md
travis.yml

Setting up travis based continous integration - Closes #9

---

LICENSE
README.md
docs/example/api.html
docs/example/experiment.html
docs/index.html

The following pull request contains my review of the documentation for lisk-js version 0.3.

Revised docs for version 0.3

---

docs/example/api.html
docs/example/js/liskjs-example.js

Fix description for lisk API
Add error message for firefox

Doc and example optimization

---

dist/lisk-js.js
docs/example/experiment.html
docs/example/js/liskjs-example.js
lib/api/liskApi.js
test/transactions/transaction.js

fixing #57 and #64

---

eslint_ecma5.json
index.js
test/transactions/transfer.js

Add test coverage for transfer.js - Fixes #50

---

.travis.yml

Speed up travis build by caching node_modules - Closes #79

---

lib/api/liskApi.js

Change testnet explorer IP address to testnet domain - Closes #91

---

lib/api/liskApi.js
test/api/liskApi.js

Improve peers selection - Fixes #96

---

lib/api/liskApi.js
test/api/liskApi.js

Removes null and false from checkOptions for sendRequests - Fixes #117

---

README.md
package.json
yuidoc.json

Bump version to 0.4.1

---

lib/transactions/multisignature.js
test/transactions/multisignature.js

Sign transaction return value - Fixes #134

---

lib/transactions/multisignature.js
test/transactions/multisignature.js

createTransaction function multisig - Fixes #136

---

.gitignore

Add coverage dir to .gitignore - Closes #160

---

eslint_ecma5.json
test/transactions/multisignature.js

Lint console statements and remove from test file - Closes #164

---

docs/example/api.html
lib/constants.js
lib/transactions/crypto.js
test/transactions/crypto.js

Move fixedPoint into constants - Closes #159

---

docs/example/api.html

Update docs for getBlock - Closes #165

---

lib/api/utils.js

Fix trimObj name - Closes #161

---

docs/example/api.html

Remove nonsense variable assignments from docs examples - Closes #167

---

test/api/liskApi.js

Use return instead of done in async tests - Closes #155

---

.eslintrc.json
test/api/liskApi.js
test/time/slots.js
test/transactions/crypto.js
test/transactions/crypto/index.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js
test/utils/mnemonic.js

Make sure all assertions are called - Closes #174

---

lib/transactions/crypto.js
test/transactions/crypto.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/vote.js

Replace deprecated new Buffer - Closes #184

---

.eslintrc.json
lib/api/liskApi.js
lib/api/parseTransaction.js
lib/transactions/dapp.js
lib/transactions/delegate.js
lib/transactions/multisignature.js
lib/transactions/signature.js
lib/transactions/transaction.js
lib/transactions/transfer.js
lib/transactions/vote.js
test/api/liskApi.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js

Use offsets in transaction creation - Closes #191

---

lib/transactions/dapp.js
lib/transactions/delegate.js
lib/transactions/multisignature.js
lib/transactions/signature.js
lib/transactions/transaction.js
lib/transactions/transfer.js
lib/transactions/vote.js

Add yuidoc annotations for timeOffset - Closes #197

---

package-lock.json
package.json
yarn.lock

Git hook validation - Closes #187

---

eslint_ecma5.json
lib/api/liskApi.js
lib/api/parseTransaction.js
lib/transactions/dapp.js
lib/transactions/delegate.js
lib/transactions/multisignature.js
lib/transactions/signature.js
lib/transactions/transaction.js
lib/transactions/transfer.js
lib/transactions/vote.js
test/api/liskApi.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js

Just cherry-picked commits for 0.4.4 base branch.

Retry timestamp in future failures

---

package.json

Correct licence format - Closes #206

---

test/transactions/crypto.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/vote.js

Replace new Buffer in test files - Closes #184

---

.editorconfig

Add editor config - Closes #212

---

test/common.js
test/transactions/crypto.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/vote.js

~~Merge #213 first~~
Closes #209

Refactor hex checks - Closes #209

---

lib/utils/mnemonic.js

Simplify mnemonic generation - Closes #215

---

test/api/liskApi.js
test/api/parseTransaction.js
test/mocha.opts
test/setup.js
test/time/slots.js
test/transactions/crypto.js
test/transactions/crypto/index.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js
test/utils/mnemonic.js

Closes #189 
Removing the common import also makes it very clear when our tests are not atomic for future refactors.
I had to change some of the hardcoded public keys to get the tests passing again, which I don't currently understand.

Standardise test setup - Closes #189

---

src/api/liskApi.js
src/time/slots.js
src/transactions/dapp.js
src/transactions/delegate.js
src/transactions/multisignature.js
src/transactions/signature.js
src/transactions/transaction.js
src/transactions/transfer.js
src/transactions/vote.js
test/api/liskApi.js
test/time/slots.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js

Use seconds in time offset - Closes #205

---

package.json

Build prepublishOnly instead of postinstall - Closes #221

---

.npmignore

Add npmignore file - Closes #220

---

package.json

Update entry point in package.json - Closes #256

---

.eslintignore
Gruntfile.js

Add .eslintignore file - Closes #265

---

test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js

Closes #267 
Some tests have been given a `.skip` but these will be added back in through the course of #178

Use separate test files for separate API modules - Closes #267

---

test/transactions/transfer.js

Make transfer tests atomic - Closes #273

---

src/transactions/signature.js
src/transactions/utils.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js

Allows empty string as secondSecret - Closes #285

---

test/transactions/transaction.js

Make transaction tests atomic - Closes #272

---

test/transactions/signature.js

Make signature tests atomic - Closes #271

---

test/transactions/multisignature.js

Make multisignature transaction tests atomic - Closes #270

---

test/transactions/delegate.js

Make delegate transaction tests atomic - Closes #269

---

src/api/liskApi.js
test/api/liskApi.js

Renames list to get functions - Closes #244

---

src/transactions/dapp.js
test/transactions/dapp.js

Closes #268 
@Tosch110 Please review option validation carefully as I'm not 100% on required behaviour here.

Make dapp transaction tests atomic - Closes #268

---

src/transactions/delegate.js
test/transactions/delegate.js

from asset.delegate object
Closes #296

Removes publicKey in createDelegate function - Closes #296

---

src/time/slots.js
test/time/slots.js

Make time slots tests atomic - Closes #276

---

src/transactions/dapp.js
test/transactions/dapp.js

Complete dapp transaction coverage

---

src/api/liskApi.js
test/api/liskApi.js

Refactor API module for new API design - Closes #242

---

test/utils/mnemonic.js
test/utils/words.js

Make mnemonic tests atomic - Closes #281

---

Gruntfile.js
Jenkinsfile
src/api/privateApi.js
src/api/utils.js
src/constants.js
src/index.js
src/transactions/crypto/index.js
src/transactions/utils.js
test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js
test/setup.js
test/time/slots.js
test/transactions/crypto.js
test/transactions/crypto/index.js
test/transactions/dapp.js
test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js
test/utils/mnemonic.js
test/utils/words.js

Add license headers - Closes #211

---

test/transactions/utils.js

Add tests for transactions utils

---

test/setup.js

Import babel-polyfill in tests - Closes #317

---

.babelrc
test/setup.js

Remove babel-polyfill from .babelrc plugins - Closes #316

---

src/api/liskApi.js
test/api/liskApi.js

Add dapp api helper - Closes #290

---

.babelrc
.nycrc
package-lock.json
package.json
yarn.lock

Add babel-plugin-istanbul - Closes #309

---

src/api/liskApi.js
src/api/privateApi.js
test/api/liskApi.js
test/api/privateApi.js

Closes #277 
Skips added for 2 additional tests, but these will be reintroduced as part of #278 
Three lines are partially uncovered, but this will be resolved in #314

Make Lisk API tests atomic - Closes #277

---

README.md

Change cdn in README to master branch - Closes #323

---

README.md

Change cdn to master branch, update version badge

CDN update to master, version badge to 0.4.5 in README

---

.eslintignore

Adds browsertest/ to .eslintignore - Closes #338

---

.babelrc
package-lock.json
package.json
src/api/liskApi.js
src/api/privateApi.js
test/api/liskApi.js
test/api/privateApi.js
yarn.lock

Make private api test atomic - Closes #278

---

.gitignore

lcov testfolder gitignore - Closes #344

---

src/transactions/dapp.js
src/transactions/delegate.js
src/transactions/multisignature.js
src/transactions/signature.js
src/transactions/transaction.js
src/transactions/transfer.js
src/transactions/utils.js
src/transactions/vote.js

Change crypto imports - Closes #229

---

package-lock.json
yarn.lock

Update lockfiles for crypto-browserify removal - Closes #333

---

test/constants.js
test/setup.js

Add tests for constants module - Closes #352

---

test/transactions/delegate.js
test/transactions/multisignature.js
test/transactions/signature.js
test/transactions/transaction.js
test/transactions/transfer.js
test/transactions/vote.js

Add id property test to all transaction tests - Closes #353

---

package.json
src/crypto/convert.js
src/index.js
src/utils/mnemonic.js

Remove buffer dependency - Closes #332

---

package.json

Removes now scripts - Closes #364

---

src/api/liskApi.js
src/api/privateApi.js
src/api/utils.js
test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js

move utils out of private api - closes #331

---

src/api/liskApi.js
src/crypto/keys.js
test/api/liskApi.js
test/crypto/keys.js

Make LiskAPI a class

---

.npmrc

Add .npmrc file - Closes #380

---

src/api/privateApi.js
test/api/privateApi.js

Not ban provided nodes - Closes #329

---

src/crypto/sign.js
test/crypto/sign.js

Print signed message for with signing with two signatures - Closes #385

---

src/crypto/hash.js
src/crypto/index.js
src/crypto/keys.js
src/crypto/sign.js
test/crypto/convert.js
test/crypto/hash.js
test/crypto/index.js
test/crypto/keys.js
test/crypto/sign.js

Make crypto tests atomic - Closes #275

---

CONTRIBUTING.md

Update recommended emojis in CONTRIBUTING - Closes #411

---

CONTRIBUTING.md

Optimize Pull Request description for CONTRIBUTING - Closes #411

---

package.json

Remove --verbose flag from eslint npm script

---

src/transactions/1_registerSecondPassphrase.js
src/transactions/index.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/index.js

Rename registerSecondSignature to registerSecondPassphrase - Closes #423 

---

src/transactions/0_send.js
src/transactions/0_sendFromMultisignatureAccount.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
test/transactions/0_send.js
test/transactions/0_sendFromMultisignatureAccount.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js

Update transactions and tests for strings - Closes #409

---

test/_globalHooks.js
test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js
test/transactions/0_send.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js

Centralise global mocha afterEach hook - Closes #403

---

.npmignore
bin/publish_browser.sh
package.json

:house: Add npm scripts for publishing browser dist - Closes #237

---

test/transactions/0_send.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js

:white_check_mark: Revisit second secret tests - Closes #407

---

package-lock.json
package.json
test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js
test/setup.js
test/transactions/0_send.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/utils/getTransactionHash.js
yarn.lock

Use should-sinon - Closes #399

---

src/api/privateApi.js
src/api/utils.js
test/api/utils.js

Remove unhelpful api utils - Closes #311

---

src/api/liskApi.js
src/constants.js
src/transactions/0_transfer.js
src/transactions/index.js
src/transactions/utils/getTransactionBytes.js
test/api/liskApi.js
test/constants.js
test/transactions/0_transfer.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/index.js
test/transactions/utils/getTransactionBytes.js

:recycle: Rename send transaction to transfer - Closes #436

---

src/crypto/convert.js
src/crypto/sign.js
src/transactions/0_transfer.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
src/transactions/utils/getTransactionId.js
src/transactions/utils/index.js
src/transactions/utils/prepareTransaction.js
src/transactions/utils/signAndVerify.js
test/crypto/convert.js
test/crypto/sign.js
test/transactions/utils/getTransactionId.js
test/transactions/utils/index.js
test/transactions/utils/signAndVerify.js

Closes #433 
Crypto now has no dependencies on transactions
Improved tests along the way since I had to refactor them anyway.

Relocate transaction signing/verifying - Closes #433

---

src/crypto/keys.js
src/crypto/sign.js
test/crypto/keys.js
test/crypto/sign.js

:recycle: Make names consistent from raw to bytes - Closes #386

---

src/index.js
src/transactions/index.js

:seedling: Export transaction utils with lisk-js - Closes #445

---

.gitignore
README.md
bin/publish_browser.sh
dist-browser/README.md

Document browser release - Closes #442

---

package-lock.json
package.json
src/index.js
yarn.lock

Bitcore to bitcoinjs mnemonics - Closes #453

---

bin/prestart.sh
bin/start.sh
package.json

Add npm start script - Closes #457

---

src/api/liskApi.js
test/api/liskApi.js

Return a promise in broadcastSignedTransaction - Closes #378

---

src/crypto/convert.js
src/transactions/utils/getTransactionBytes.js
src/transactions/utils/getTransactionId.js
test/crypto/convert.js

:recycle: Remove bignumber usage from transactions - Closes #449

---

src/api/liskApi.js
src/api/privateApi.js
src/api/utils.js
src/constants.js
src/crypto/convert.js
src/crypto/hash.js
src/crypto/keys.js
src/crypto/sign.js
src/transactions/0_transfer.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
src/transactions/utils/getAddressAndPublicKeyFromRecipientData.js
src/transactions/utils/getTransactionBytes.js
src/transactions/utils/getTransactionHash.js
src/transactions/utils/getTransactionId.js
src/transactions/utils/signAndVerify.js
test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js

Closes #219 for now.
We should revisit this once we've thought more about state management in the API module.

Purify functions - Closes #219

---

Gruntfile.js

Closes #459 
Most of the changes are from Prettier. Only relevant change is line 28.

Preserve dist-browser README - Closes #459

---

src/crypto/convert.js

:bug: Fix dist-node - Closes #465

---

.babelrc
package-lock.json
package.json
src/index.js
test/setup.js
yarn.lock

Remove babel polyfill - Closes #468

---

.lintstagedrc
.lintstagedrc.json
.prettierrc.json
package.json

Use a prettier config file - Closes #470

---

src/api/liskApi.js
src/crypto/keys.js
src/crypto/sign.js
src/transactions/0_transfer.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
src/transactions/utils/prepareTransaction.js
src/transactions/utils/signAndVerify.js
test/api/liskApi.js
test/crypto/convert.js
test/crypto/keys.js
test/crypto/sign.js
test/transactions/0_transfer.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/utils/prepareTransaction.js
test/transactions/utils/signAndVerify.js

Use passphrase/minimum names more consistently - Closes #471

---

browsertest/config.json
config.json
src/api/liskApi.js
test/api/liskApi.js

Update to ssl as default in the config - Closes #492

---

src/transactions/utils/index.js
src/transactions/utils/validatePublicKey.js
test/transactions/utils/validatePublicKey.js

:seedling: validate public keys - Closes #488

---

src/crypto/encrypt.js
test/crypto/encrypt.js

Improve decrypt message secret error - Closes #473

---

src/api/liskApi.js
test/api/liskApi.js

Add api method for broadcasting signatures - Closes #484

---

src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/utils/format.js
src/transactions/utils/index.js
src/transactions/utils/validation.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/utils/format.js
test/transactions/utils/validation.js

Validate public keys and syntax in transaction creators - Closes #487

---

test/api/liskApi.js
test/api/privateApi.js
test/api/utils.js
test/constants.js
test/crypto/convert.js
test/crypto/encrypt.js
test/crypto/hash.js
test/crypto/index.js
test/crypto/keys.js
test/crypto/sign.js
test/transactions/0_transfer.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/index.js
test/transactions/utils/getAddressAndPublicKeyFromRecipientData.js
test/transactions/utils/getTransactionBytes.js
test/transactions/utils/getTransactionHash.js
test/transactions/utils/getTransactionId.js
test/transactions/utils/index.js
test/transactions/utils/prepareTransaction.js
test/transactions/utils/signAndVerify.js
test/transactions/utils/time.js

Return from all it blocks - Closes #499

---

src/transactions/0_transfer.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
test/transactions/0_transfer.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/index.js

Create unsigned transactions - Closes #490

---

src/api/liskApi.js
test/api/liskApi.js

Note that transactions will not be successfully broadcast currently as transaction creators need to be updated in https://github.com/LiskHQ/lisk-js/issues/482

Update broadcast methods

---

src/transactions/0_transfer.js
src/transactions/1_registerSecondPassphrase.js
src/transactions/2_registerDelegate.js
src/transactions/3_castVotes.js
src/transactions/4_registerMultisignatureAccount.js
src/transactions/5_createDapp.js
src/transactions/6_transferIntoDapp.js
src/transactions/7_transferOutOfDapp.js
src/transactions/utils/index.js
src/transactions/utils/wrapTransactionCreator.js
test/transactions/0_transfer.js
test/transactions/1_registerSecondPassphrase.js
test/transactions/2_registerDelegate.js
test/transactions/3_castVotes.js
test/transactions/4_registerMultisignatureAccount.js
test/transactions/5_createDapp.js
test/transactions/6_transferIntoDapp.js
test/transactions/7_transferOutOfDapp.js
test/transactions/utils/prepareTransaction.js
test/transactions/utils/wrapTransactionCreator.js

Closes #508 
~~This is a WIP: I thought I'd get some feedback on whether the scope of my function is correct before writing unit tests for it. (So far the existing transaction-creator unit tests have been sufficient to guarantee the refactoring does not alter transaction-creator functionality.)~~

Add HOF for transaction creators - Closes #508

---

.gitignore
Gruntfile.js
browsertest/setup.js
cypress.json
src/crypto/encrypt.js
test/crypto/encrypt.js

Closes #501 
~~Note: timing tests cover Node and browser.~~
Note: timing tests are skipped in the browser.

Use pbkdf2 when encrypting passphrases - Closes #501

---

test/crypto/encrypt.js

Exclude encryption integration test in browser - Closes #528

---

package-lock.json
src/transactions/utils/index.js
src/transactions/utils/signRawTransaction.js
test/transactions/utils/signRawTransaction.js

Sign raw transactions - Closes #507

---

src/passphrase/index.js
src/passphrase/validation.js
test/passphrase/index.js
test/passphrase/validation.js

:seedling: Add passphrase validation functions - Closes #456

---

lib/api/liskApi.js
test/api/liskApi.js

Testsuite for sendRequest failures - Closes #537

---

src/api/utils.js
test/api/liskApi.js

Set accept header - Closes #515

---

src/api/liskApi.js
src/api/utils.js
test/api/liskApi.js
test/api/utils.js

Remove support for callbacks - Closes #527

---

src/crypto/sign.js
test/crypto/sign.js
test/transactions/utils/getTransactionBytes.js

Change signature from base64 to hex - Closes #536

---

src/api/lisk_api.js
src/api/resources/delegates.js
src/api/resources/index.js
src/api/resources/node.js
src/api/resources/nodes.js
src/api/resources/peers.js
src/api/resources/signatures.js
src/api/resources/transactions.js
src/constants/index.js
test/api/lisk_api.js
test/api/resources/accounts.js
test/api/resources/blocks.js
test/api/resources/dapps.js
test/api/resources/delegates.js
test/api/resources/index.js
test/api/resources/node.js
test/api/resources/nodes.js
test/api/resources/peers.js
test/api/resources/signatures.js
test/api/resources/transactions.js
test/api/resources/voters.js
test/api/resources/votes.js
test/constants/constants.js

Closes #482 
~Merge after #512~

Update API definition to match v1.0.0 - Closes #482

---

src/api_client/api_client.js
src/lisk-constants/index.js
test/api_client/api_client.js
test/lisk-constants/index.js

These changes were accidentally merged into `development` in PR #629 .
This PR is based on `1.0.0`.

Add betanet constants - Closes #628

---

Jenkinsfile

Jenkinsfile lacked slack integration
I added it
I'm pushing this pull request, if it works, we'll see a result
* The PR solves #664 
* Tests pass

Update Jenkinsfile to implement slack notifications

---

src/transactions/0_transfer.js
src/transactions/constants.js
test/transactions/0_transfer.js
test/transactions/constants.js

Removing additional fee from type 0 with data discussed in LiskHQ/lisk#2033.
`npm t`
* The PR solves #671 
* Tests pass

Remove additional fee from type 0 with data - Closes #671

---

package.json
src/cryptography/convert.js
src/cryptography/encrypt.js
src/cryptography/hash.js
src/cryptography/keys.js
src/cryptography/sign.js
src/index.js
test/setup.js

JS-Nacl is not compatible with RN medium.
Make sure Lisk Elements in injectable in RN
* The PR solves #393
* Tests pass

Update dependencies - Resolves #393

---

README.md
docs/ISSUE_TEMPLATE.md

The README needed to be updated.
Updated it.
👓 
* The PR solves #581 
* Tests pass

Update readme - Closes #581

---

README.md

The example code in the README was incorrect.
Used correct code.
Follow the steps in the README.
* The PR solves #723 
* Tests pass

Correct README example code - Closes #723

---

package.json
packages/lisk-api-client/src/api_client.js
packages/lisk-api-client/test/api_client.js
packages/lisk-cryptography/src/convert.js
packages/lisk-transactions/src/utils/get_transaction_bytes.js
packages/lisk-transactions/src/utils/validation.js

The root prettier version was different to the packages', causing conflicts.
Upgraded the root version and formatted the codebase.
`npm run format` and check no changes are made.
* The PR solves #730 
* Tests pass

Standardise prettier - Closes #730

---

package.json
packages/lisk-api-client/package.json
packages/lisk-constants/package.json
packages/lisk-cryptography/package.json
packages/lisk-elements/package.json
packages/lisk-passphrase/package.json
packages/lisk-transactions/package.json

Coveralls was adding overhead and not providing much value.
Removed coveralls.
Check Jenkins.
* The PR solves #727 
* Tests pass

Remove coveralls - Closes #727

---

.gitignore
README.md
package.json

postinstall script was causing error on windows.
Removed the postinstall script and updated Readme file accordingly.
* The PR resolves #724 
* Tests pass

Remove postinstall script - closes #724

---

packages/lisk-api-client/package.json

* The PR resolves #743 
* Tests pass

Remove equal sign from dependencies - closes #743

---

package.json
packages/lisk-api-client/package.json
packages/lisk-api-client/scripts
packages/lisk-constants/package.json
packages/lisk-constants/scripts
packages/lisk-cryptography/package.json
packages/lisk-cryptography/scripts
packages/lisk-elements/package.json
packages/lisk-elements/scripts/clean.sh
packages/lisk-passphrase/package.json
packages/lisk-passphrase/scripts
packages/lisk-transactions/package.json
packages/lisk-transactions/scripts
scripts/init.sh
templates/scripts.tmpl/clean.sh

* The PR resolves #748, resolves #747 
* Tests pass

Create Symlinks Script - #closes 748

---

packages/lisk-elements/scripts/start.sh

* The PR resolves #754 
* Tests pass

Rename global variable `LiskElements` to `lisk` - closes #754

---

.npmignore

We needed to update the `.npmignore` file.
Updated it.
Publish to npm.
* The PR resolves #766 
* Tests pass

Update .npmignore - Closes #766

---

docs/CONTRIBUTING.md

We didn't mention we're using git flow.
I added a mention and a link to learn more.
🤓 
* The PR resolves #755 
* Tests pass

Add note about using git flow - Closes #755

---

packages/lisk-transactions/fixtures/invalid_transactions.json
packages/lisk-transactions/fixtures/transactions.json
packages/lisk-transactions/src/utils/validation/validate_transaction.js
packages/lisk-transactions/test/utils/validation/validate_transaction.js
packages/lisk-transactions/test/utils/validation/validator.js

Test for validating the transaction were missing.
Add tests for `validate_transaction` and `validator` using fixtures and several constant transactions.
`npm t`
* The PR resolves #764 
* Tests pass

Add tests for validate transactions - Closes #764

---

.eslintrc.json
Jenkinsfile
package.json
packages/lisk-api-client/package.json
packages/lisk-constants/package.json
packages/lisk-cryptography/.eslintrc.json
packages/lisk-cryptography/package.json
packages/lisk-cryptography/src/convert.js
packages/lisk-elements/package.json
packages/lisk-passphrase/package.json
packages/lisk-transactions/package.json
packages/lisk-transactions/src/0_transfer.js
packages/lisk-transactions/test/_setup.js

Our dependencies hadn't been updated.
Updated them.
Install, build, lint, test etc.
* The PR resolves #746 
* Tests pass

Update dependencies - Closes #746

---

package-lock.json
packages/lisk-constants/package-lock.json
packages/lisk-transactions/package-lock.json
packages/lisk-transactions/src/0_transfer.js
packages/lisk-transactions/src/utils/index.js
packages/lisk-transactions/src/utils/validation/index.js
packages/lisk-transactions/src/utils/validation/schema.js
packages/lisk-transactions/src/utils/validation/validation.js
packages/lisk-transactions/src/utils/validation/validator.js
packages/lisk-transactions/test/0_transfer.js
packages/lisk-transactions/test/utils/validation/validate_transaction.js
packages/lisk-transactions/test/utils/validation/validation.js
packages/lisk-transactions/test/utils/validation/validator.js

Transfer transactions (type 0) should not allow an amount of 0.
Add validator for transfer transaction amount. Enforce 0 amount for other transaction types in schema. 
Create a transfer transaction with amount 0.
* The PR resolves #783
* Tests pass

Disallow 0 amounts for transfer transactions - Closes #783

---

package-lock.json
package.json
packages/lisk-api-client/package-lock.json
packages/lisk-client/package-lock.json
packages/lisk-constants/package-lock.json
packages/lisk-cryptography/package-lock.json
packages/lisk-cryptography/package.json
packages/lisk-elements/package-lock.json
packages/lisk-passphrase/package-lock.json
packages/lisk-transactions/package-lock.json

package-lock.json merging failed during the merge commit
delete the package-lock.json and regenerate it.
```
npm run clean
npm run clean:node_modules
npm i
npm run build
```
* The PR resolves #803
* Tests pass

Fix package-lock.json

---

packages/lisk-constants/.nycrc
templates/.nycrc-ts.tmpl

Add a new template of `.nycrc` file for packages being migrated to TypeScript.
This PR closes #814 
* The PR resolves #814
* Tests pass

Add .nycrc template for TypeScript files - Closes #814

---

package-lock.json
packages/lisk-cryptography/package-lock.json

Broken package-lock.json in cryptography package
Delete package-lock.json. Clean node_modules. Reinstall modules and regenerate new package-lock.json.
npm i and npm run build in cryptography package
* The PR resolves #828
* Tests pass

Fix cryptography package-lock.json - Closes #828

---

packages/lisk-transactions/package.json
packages/lisk-transactions/src/3_cast_votes.ts
packages/lisk-transactions/test/0_transfer.ts
packages/lisk-transactions/test/1_register_second_passphrase.ts
packages/lisk-transactions/test/2_register_delegate.ts
packages/lisk-transactions/test/3_cast_votes.ts
packages/lisk-transactions/test/4_register_multisignature_account.ts
packages/lisk-transactions/test/5_create_dapp.ts
packages/lisk-transactions/test/create_signature_object.ts

transactions module `package.json` was not configured correctly and not testing the root test files.
Also added one missing test.
Change the test script to include the root files
`npm t`
* The PR resolves #843 
* Merge after #842 
* Tests pass

Fix transaction test to cover root files

---

packages/lisk-p2p/package-lock.json
packages/lisk-p2p/package.json
packages/lisk-p2p/src/errors/index.ts
packages/lisk-p2p/src/errors/p2p_error.ts
packages/lisk-p2p/src/errors/peer_transport_error.ts
packages/lisk-p2p/src/p2p.ts
packages/lisk-p2p/src/p2p_types.ts
packages/lisk-p2p/src/peer.ts
packages/lisk-p2p/src/peer_pool.ts
packages/lisk-p2p/test/integration/p2p.ts

Add PeerPool and set up integration tests.

Add PeerPool and prepare integration tests

---

packages/lisk-transaction-pool/src/transaction_pool.ts
packages/lisk-transaction-pool/test/transaction_pool.ts

Add functionality for adding the transaction to the verified queue
The PR resolves #877
All new code is covered with unit tests
All new code was formatted with Prettier
Linting passes
Tests pass
Commit messages follow the commit guidelines
Documentation has been added/updated

Add functionality for enqueuing transaction from client - Closes #877

---

packages/lisk-transaction-pool/src/queue.ts
packages/lisk-transaction-pool/src/transaction_pool.ts
packages/lisk-transaction-pool/test/queue.ts
packages/lisk-transaction-pool/test/transaction_pool.ts

The functionality for validating received transactions was missing.
Added functionality for validating transactions.
Run tests.
* The PR resolves #879
* Tests pass

Add functionality for validating received transactions - Closes #879
